FROM node:20-alpine

WORKDIR /app

# Kopiere package.json
COPY package*.json ./

# Installiere Abhängigkeiten
RUN npm install --legacy-peer-deps

# Kopiere den Quellcode
COPY . .

# Kopiere Environment-Datei
COPY env.local .env.local

# Build das Frontend für Production
RUN npm run build

# Exponiere Port 3000
EXPOSE 3000

# Starte den Production-Server
CMD ["npm", "run", "start"]



