apiVersion: v1
kind: ConfigMap
metadata:
  name: hd-app-config
  namespace: hd-app
data:
  NODE_ENV: "production"
  PORT: "4001"
  DATABASE_PATH: "/app/data/hd-app.db"
  PROMETHEUS_ENABLED: "true"
  METRICS_ENABLED: "true"
  # Frontend URLs
  FRONTEND_URL: "http://hd-app-frontend:3000"
  # API URLs
  API_BASE_URL: "http://hd-app-backend:4001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hd-app-frontend-config
  namespace: hd-app
data:
  NEXT_PUBLIC_API_URL: "http://hd-app-backend:4001"
  NEXT_PUBLIC_APP_NAME: "HD App"
  NEXT_PUBLIC_VERSION: "1.0.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hd-app-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alerts.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      - job_name: 'hd-app-backend'
        static_configs:
          - targets: ['hd-app-backend:4001']
        metrics_path: '/metrics/prometheus'
        scrape_interval: 10s

      - job_name: 'hd-app-frontend'
        static_configs:
          - targets: ['hd-app-frontend:3000']
        metrics_path: '/api/metrics'
        scrape_interval: 30s

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: hd-app-monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
