apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - storage.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - monitoring-deployment.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: hd-app
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: human-design-app

images:
  - name: hd-app-backend
    newTag: latest
  - name: hd-app-frontend
    newTag: latest
