// Die 64 Tore des Human Design Systems mit detaillierten Beschreibungen

export interface GateData {
  number: number;
  name: string;
  description: string;
  keywords: string[];
  center: string;
  line: number;
  hexagram: string;
  meaning: string;
  shadow: string;
  gift: string;
  siddhi: string;
  bodygraph: {
    position: { x: number; y: number };
    color: string;
  };
  channel?: string;
  oppositeGate?: number;
}

// Die 64 Tore des Human Design Systems
export const gatesData: { [key: number]: GateData } = {
  1: {
    number: 1,
    name: "Die Kreativität",
    description: "Das Tor der Kreativität und des Selbstausdrucks. Es bringt die Energie der Inspiration und des kreativen Schaffens.",
    keywords: ["Kreativität", "Inspiration", "Selbstausdruck", "Kunst", "Innovation"],
    center: "G-Zentrum",
    line: 1,
    hexagram: "Das Schöpferische",
    meaning: "Die Energie der Kreativität und des Selbstausdrucks. Du bist hier, um deine einzigartige Kreativität in die Welt zu bringen.",
    shadow: "Selbstzweifel und mangelndes Vertrauen in die eigene Kreativität",
    gift: "Natürliche Kreativität und Fähigkeit, Neues zu erschaffen",
    siddhi: "Göttliche Kreativität und Schöpfungskraft",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  2: {
    number: 2,
    name: "Die Richtung",
    description: "Das Tor der Richtung und des höheren Zwecks. Es bringt die Energie der Führung und des Lebenszwecks.",
    keywords: ["Richtung", "Zweck", "Führung", "Höheres Selbst", "Lebensweg"],
    center: "G-Zentrum",
    line: 2,
    hexagram: "Das Empfangende",
    meaning: "Die Energie der Richtung und des höheren Zwecks. Du bist hier, um deinen einzigartigen Lebensweg zu finden und zu führen.",
    shadow: "Verwirrung über den Lebenszweck und mangelnde Richtung",
    gift: "Klare Richtung und natürliche Führungsqualitäten",
    siddhi: "Göttliche Führung und höchster Zweck",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  3: {
    number: 3,
    name: "Die Schwierigkeit",
    description: "Das Tor der Schwierigkeit und des Durchbruchs. Es bringt die Energie der Transformation durch Herausforderungen.",
    keywords: ["Schwierigkeit", "Durchbruch", "Transformation", "Herausforderung", "Wachstum"],
    center: "Sakral-Zentrum",
    line: 3,
    hexagram: "Die Schwierigkeit am Anfang",
    meaning: "Die Energie der Schwierigkeit und des Durchbruchs. Du bist hier, um durch Herausforderungen zu wachsen und Durchbrüche zu erleben.",
    shadow: "Vermeidung von Herausforderungen und mangelnde Ausdauer",
    gift: "Natürliche Fähigkeit, Schwierigkeiten zu überwinden",
    siddhi: "Göttliche Transformation durch Herausforderungen",
    bodygraph: { position: { x: 70, y: 55 }, color: "#ec4899" }
  },
  4: {
    number: 4,
    name: "Die Jugendliche Torheit",
    description: "Das Tor der Jugend und des Lernens. Es bringt die Energie des Lernens und der Entwicklung.",
    keywords: ["Jugend", "Lernen", "Entwicklung", "Torheit", "Wachstum"],
    center: "G-Zentrum",
    line: 4,
    hexagram: "Die Jugendliche Torheit",
    meaning: "Die Energie der Jugend und des Lernens. Du bist hier, um zu lernen und dich kontinuierlich zu entwickeln.",
    shadow: "Mangelnde Lernbereitschaft und Starrheit",
    gift: "Natürliche Lernfähigkeit und Offenheit für Neues",
    siddhi: "Göttliche Weisheit durch ewiges Lernen",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  5: {
    number: 5,
    name: "Das Warten",
    description: "Das Tor des Wartens und der Geduld. Es bringt die Energie der Geduld und des richtigen Timings.",
    keywords: ["Warten", "Geduld", "Timing", "Rhythmus", "Natürlichkeit"],
    center: "G-Zentrum",
    line: 5,
    hexagram: "Das Warten",
    meaning: "Die Energie des Wartens und der Geduld. Du bist hier, um zu lernen, auf den richtigen Moment zu warten.",
    shadow: "Ungeduld und mangelnde Geduld",
    gift: "Natürliche Geduld und Fähigkeit, auf den richtigen Moment zu warten",
    siddhi: "Göttliche Geduld und perfektes Timing",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  6: {
    number: 6,
    name: "Der Konflikt",
    description: "Das Tor des Konflikts und der Auflösung. Es bringt die Energie der Konfliktlösung und der Harmonie.",
    keywords: ["Konflikt", "Harmonie", "Auflösung", "Beziehung", "Frieden"],
    center: "G-Zentrum",
    line: 6,
    hexagram: "Der Streit",
    meaning: "Die Energie des Konflikts und der Auflösung. Du bist hier, um Konflikte zu lösen und Harmonie zu schaffen.",
    shadow: "Konfliktvermeidung oder -eskalation",
    gift: "Natürliche Fähigkeit, Konflikte zu lösen",
    siddhi: "Göttliche Harmonie und Konfliktlösung",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  7: {
    number: 7,
    name: "Die Rolle des Selbst",
    description: "Das Tor der Führung und der Rolle. Es bringt die Energie der natürlichen Führung und Autorität.",
    keywords: ["Führung", "Rolle", "Autorität", "Selbst", "Verantwortung"],
    center: "G-Zentrum",
    line: 7,
    hexagram: "Das Heer",
    meaning: "Die Energie der Führung und der Rolle. Du bist hier, um zu führen und deine natürliche Autorität zu leben.",
    shadow: "Mangelnde Führungsqualitäten oder Machtmissbrauch",
    gift: "Natürliche Führungsqualitäten und Autorität",
    siddhi: "Göttliche Führung und Autorität",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  8: {
    number: 8,
    name: "Der Beitrag",
    description: "Das Tor des Beitrags und der Teilhabe. Es bringt die Energie des Beitrags zur Gemeinschaft.",
    keywords: ["Beitrag", "Teilhabe", "Gemeinschaft", "Zusammenarbeit", "Service"],
    center: "Kehle-Zentrum",
    line: 8,
    hexagram: "Die Zusammenarbeit",
    meaning: "Die Energie des Beitrags und der Teilhabe. Du bist hier, um zur Gemeinschaft beizutragen und zusammenzuarbeiten.",
    shadow: "Mangelnde Bereitschaft zu teilen oder zu kooperieren",
    gift: "Natürliche Fähigkeit, zur Gemeinschaft beizutragen",
    siddhi: "Göttlicher Service und Beitrag",
    bodygraph: { position: { x: 50, y: 40 }, color: "#06b6d4" }
  },
  9: {
    number: 9,
    name: "Der Fokus",
    description: "Das Tor des Fokus und der Konzentration. Es bringt die Energie der Konzentration und des Fokus.",
    keywords: ["Fokus", "Konzentration", "Detail", "Präzision", "Aufmerksamkeit"],
    center: "Sakral-Zentrum",
    line: 9,
    hexagram: "Der kleine Zähme",
    meaning: "Die Energie des Fokus und der Konzentration. Du bist hier, um dich zu konzentrieren und Details zu beachten.",
    shadow: "Mangelnde Konzentration oder übertriebener Perfektionismus",
    gift: "Natürliche Fähigkeit, sich zu konzentrieren",
    siddhi: "Göttlicher Fokus und Konzentration",
    bodygraph: { position: { x: 70, y: 55 }, color: "#ec4899" }
  },
  10: {
    number: 10,
    name: "Das Treten",
    description: "Das Tor des Tretens und des Gehens. Es bringt die Energie der Bewegung und des Fortschritts.",
    keywords: ["Treten", "Gehen", "Bewegung", "Fortschritt", "Schritt"],
    center: "G-Zentrum",
    line: 10,
    hexagram: "Das Treten",
    meaning: "Die Energie des Tretens und des Gehens. Du bist hier, um voranzugehen und deinen Weg zu gehen.",
    shadow: "Mangelnde Bewegung oder zielloses Umherirren",
    gift: "Natürliche Fähigkeit, voranzugehen",
    siddhi: "Göttliche Bewegung und Fortschritt",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  // Weitere Tore werden hier fortgesetzt...
  11: {
    number: 11,
    name: "Die Ideen",
    description: "Das Tor der Ideen und Konzepte. Es bringt die Energie der Ideenfindung und des Konzeptualisierens.",
    keywords: ["Ideen", "Konzepte", "Gedanken", "Innovation", "Kreativität"],
    center: "Ajna-Zentrum",
    line: 11,
    hexagram: "Der Friede",
    meaning: "Die Energie der Ideen und Konzepte. Du bist hier, um Ideen zu entwickeln und zu konzeptualisieren.",
    shadow: "Mangelnde Ideen oder chaotisches Denken",
    gift: "Natürliche Fähigkeit, Ideen zu entwickeln",
    siddhi: "Göttliche Ideen und Konzepte",
    bodygraph: { position: { x: 50, y: 25 }, color: "#8b5cf6" }
  },
  12: {
    number: 12,
    name: "Die Zurückhaltung",
    description: "Das Tor der Zurückhaltung und der Vorsicht. Es bringt die Energie der Vorsicht und der Zurückhaltung.",
    keywords: ["Zurückhaltung", "Vorsicht", "Warten", "Geduld", "Stille"],
    center: "Kehle-Zentrum",
    line: 12,
    hexagram: "Die Stille",
    meaning: "Die Energie der Zurückhaltung und der Vorsicht. Du bist hier, um vorsichtig zu sein und zu warten.",
    shadow: "Übertriebene Vorsicht oder mangelnde Zurückhaltung",
    gift: "Natürliche Vorsicht und Zurückhaltung",
    siddhi: "Göttliche Zurückhaltung und Stille",
    bodygraph: { position: { x: 50, y: 40 }, color: "#06b6d4" }
  },
  13: {
    number: 13,
    name: "Der Zuhörer",
    description: "Das Tor des Zuhörens und der Empathie. Es bringt die Energie des Zuhörens und der Empathie.",
    keywords: ["Zuhören", "Empathie", "Verständnis", "Mitgefühl", "Hilfe"],
    center: "Kehle-Zentrum",
    line: 13,
    hexagram: "Der Zuhörer",
    meaning: "Die Energie des Zuhörens und der Empathie. Du bist hier, um zuzuhören und empathisch zu sein.",
    shadow: "Mangelnde Empathie oder übertriebene Einmischung",
    gift: "Natürliche Fähigkeit, zuzuhören und empathisch zu sein",
    siddhi: "Göttliches Zuhören und Empathie",
    bodygraph: { position: { x: 50, y: 40 }, color: "#06b6d4" }
  },
  14: {
    number: 14,
    name: "Die Macht",
    description: "Das Tor der Macht und des Reichtums. Es bringt die Energie der Macht und des materiellen Erfolgs.",
    keywords: ["Macht", "Reichtum", "Erfolg", "Material", "Besitz"],
    center: "Sakral-Zentrum",
    line: 14,
    hexagram: "Der große Besitz",
    meaning: "Die Energie der Macht und des Reichtums. Du bist hier, um Macht und materiellen Erfolg zu erlangen.",
    shadow: "Machtmissbrauch oder mangelnde Macht",
    gift: "Natürliche Fähigkeit, Macht und Reichtum zu erlangen",
    siddhi: "Göttliche Macht und Reichtum",
    bodygraph: { position: { x: 70, y: 55 }, color: "#ec4899" }
  },
  15: {
    number: 15,
    name: "Die Bescheidenheit",
    description: "Das Tor der Bescheidenheit und der Demut. Es bringt die Energie der Bescheidenheit und der Demut.",
    keywords: ["Bescheidenheit", "Demut", "Einfachheit", "Natürlichkeit", "Authentizität"],
    center: "G-Zentrum",
    line: 15,
    hexagram: "Die Bescheidenheit",
    meaning: "Die Energie der Bescheidenheit und der Demut. Du bist hier, um bescheiden und demütig zu sein.",
    shadow: "Übertriebene Bescheidenheit oder Arroganz",
    gift: "Natürliche Bescheidenheit und Demut",
    siddhi: "Göttliche Bescheidenheit und Demut",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  16: {
    number: 16,
    name: "Die Begeisterung",
    description: "Das Tor der Begeisterung und des Enthusiasmus. Es bringt die Energie der Begeisterung und des Enthusiasmus.",
    keywords: ["Begeisterung", "Enthusiasmus", "Leidenschaft", "Energie", "Motivation"],
    center: "Kehle-Zentrum",
    line: 16,
    hexagram: "Die Begeisterung",
    meaning: "Die Energie der Begeisterung und des Enthusiasmus. Du bist hier, um begeistert und enthusiastisch zu sein.",
    shadow: "Mangelnde Begeisterung oder übertriebener Enthusiasmus",
    gift: "Natürliche Begeisterung und Enthusiasmus",
    siddhi: "Göttliche Begeisterung und Enthusiasmus",
    bodygraph: { position: { x: 50, y: 40 }, color: "#06b6d4" }
  },
  17: {
    number: 17,
    name: "Die Ansichten",
    description: "Das Tor der Ansichten und Meinungen. Es bringt die Energie der Meinungsbildung und der Ansichten.",
    keywords: ["Ansichten", "Meinungen", "Perspektive", "Standpunkt", "Überzeugung"],
    center: "Ajna-Zentrum",
    line: 17,
    hexagram: "Die Ansichten",
    meaning: "Die Energie der Ansichten und Meinungen. Du bist hier, um Ansichten zu entwickeln und Meinungen zu bilden.",
    shadow: "Mangelnde Meinungen oder starre Ansichten",
    gift: "Natürliche Fähigkeit, Ansichten zu entwickeln",
    siddhi: "Göttliche Ansichten und Weisheit",
    bodygraph: { position: { x: 50, y: 25 }, color: "#8b5cf6" }
  },
  18: {
    number: 18,
    name: "Die Korrektur",
    description: "Das Tor der Korrektur und Verbesserung. Es bringt die Energie der Korrektur und Verbesserung.",
    keywords: ["Korrektur", "Verbesserung", "Reparatur", "Heilung", "Wiederherstellung"],
    center: "Milz-Zentrum",
    line: 18,
    hexagram: "Die Korrektur",
    meaning: "Die Energie der Korrektur und Verbesserung. Du bist hier, um zu korrigieren und zu verbessern.",
    shadow: "Mangelnde Bereitschaft zu korrigieren oder übertriebene Kritik",
    gift: "Natürliche Fähigkeit, zu korrigieren und zu verbessern",
    siddhi: "Göttliche Korrektur und Heilung",
    bodygraph: { position: { x: 30, y: 55 }, color: "#f59e0b" }
  },
  19: {
    number: 19,
    name: "Die Annäherung",
    description: "Das Tor der Annäherung und des Herangehens. Es bringt die Energie der Annäherung und des Herangehens.",
    keywords: ["Annäherung", "Herangehen", "Nähe", "Beziehung", "Verbindung"],
    center: "Wurzel-Zentrum",
    line: 19,
    hexagram: "Die Annäherung",
    meaning: "Die Energie der Annäherung und des Herangehens. Du bist hier, um dich zu nähern und Beziehungen aufzubauen.",
    shadow: "Mangelnde Annäherung oder übertriebene Nähe",
    gift: "Natürliche Fähigkeit, sich zu nähern",
    siddhi: "Göttliche Annäherung und Verbindung",
    bodygraph: { position: { x: 50, y: 85 }, color: "#7c3aed" }
  },
  20: {
    number: 20,
    name: "Die Betrachtung",
    description: "Das Tor der Betrachtung und Reflexion. Es bringt die Energie der Betrachtung und Reflexion.",
    keywords: ["Betrachtung", "Reflexion", "Beobachtung", "Achtsamkeit", "Bewusstsein"],
    center: "Kehle-Zentrum",
    line: 20,
    hexagram: "Die Betrachtung",
    meaning: "Die Energie der Betrachtung und Reflexion. Du bist hier, um zu betrachten und zu reflektieren.",
    shadow: "Mangelnde Reflexion oder übertriebene Betrachtung",
    gift: "Natürliche Fähigkeit, zu betrachten und zu reflektieren",
    siddhi: "Göttliche Betrachtung und Bewusstsein",
    bodygraph: { position: { x: 50, y: 40 }, color: "#06b6d4" }
  },
  21: {
    number: 21,
    name: "Die Kontrolle",
    description: "Das Tor der Kontrolle und des Managements. Es bringt die Energie der Führung und Kontrolle.",
    keywords: ["Kontrolle", "Management", "Führung", "Autorität", "Disziplin"],
    center: "Herz-Zentrum",
    line: 1,
    hexagram: "Das Durchdringende",
    meaning: "Die Energie der Kontrolle und des Managements. Du bist hier, um zu kontrollieren und zu führen.",
    shadow: "Übertriebene Kontrolle oder mangelnde Führung",
    gift: "Natürliche Führungsqualitäten und Kontrollfähigkeit",
    siddhi: "Göttliche Kontrolle und Führung",
    bodygraph: { position: { x: 45, y: 50 }, color: "#ef4444" }
  },
  22: {
    number: 22,
    name: "Die Gnade",
    description: "Das Tor der Gnade und Eleganz. Es bringt die Energie der Schönheit und Anmut.",
    keywords: ["Gnade", "Eleganz", "Schönheit", "Anmut", "Kunst"],
    center: "Herz-Zentrum",
    line: 2,
    hexagram: "Das Sanfte",
    meaning: "Die Energie der Gnade und Eleganz. Du bist hier, um Schönheit und Anmut zu bringen.",
    shadow: "Mangelnde Eleganz oder übertriebene Eitelkeit",
    gift: "Natürliche Eleganz und künstlerische Fähigkeiten",
    siddhi: "Göttliche Schönheit und Anmut",
    bodygraph: { position: { x: 55, y: 50 }, color: "#f59e0b" }
  },
  23: {
    number: 23,
    name: "Die Spaltung",
    description: "Das Tor der Spaltung und des Durchbruchs. Es bringt die Energie der Transformation.",
    keywords: ["Spaltung", "Durchbruch", "Transformation", "Veränderung", "Neubeginn"],
    center: "Kehlkopf-Zentrum",
    line: 3,
    hexagram: "Das Abgründige",
    meaning: "Die Energie der Spaltung und des Durchbruchs. Du bist hier, um zu transformieren.",
    shadow: "Zerstörerische Spaltung oder Widerstand gegen Veränderung",
    gift: "Natürliche Fähigkeit zur Transformation und zum Durchbruch",
    siddhi: "Göttliche Transformation und Neubeginn",
    bodygraph: { position: { x: 50, y: 45 }, color: "#8b5cf6" }
  },
  24: {
    number: 24,
    name: "Die Rationalisierung",
    description: "Das Tor der Rationalisierung und des Verstehens. Es bringt die Energie des logischen Denkens.",
    keywords: ["Rationalisierung", "Verstehen", "Logik", "Denken", "Wissen"],
    center: "Kehlkopf-Zentrum",
    line: 4,
    hexagram: "Die Wiederkehr",
    meaning: "Die Energie der Rationalisierung und des Verstehens. Du bist hier, um zu verstehen und zu rationalisieren.",
    shadow: "Übertriebene Rationalisierung oder mangelndes Verständnis",
    gift: "Natürliche Fähigkeit zu verstehen und zu rationalisieren",
    siddhi: "Göttliches Verstehen und Wissen",
    bodygraph: { position: { x: 50, y: 55 }, color: "#06b6d4" }
  },
  25: {
    number: 25,
    name: "Die Unschuld",
    description: "Das Tor der Unschuld und des Vertrauens. Es bringt die Energie der Reinheit und des Glaubens.",
    keywords: ["Unschuld", "Vertrauen", "Reinheit", "Glaube", "Natürlichkeit"],
    center: "Herz-Zentrum",
    line: 5,
    hexagram: "Das Unschuldige",
    meaning: "Die Energie der Unschuld und des Vertrauens. Du bist hier, um Vertrauen und Reinheit zu bringen.",
    shadow: "Naivität oder mangelndes Vertrauen",
    gift: "Natürliche Unschuld und Vertrauensfähigkeit",
    siddhi: "Göttliche Reinheit und Glaube",
    bodygraph: { position: { x: 45, y: 60 }, color: "#10b981" }
  },
  26: {
    number: 26,
    name: "Der Trickster",
    description: "Das Tor des Tricksters und der List. Es bringt die Energie der Cleverness und Strategie.",
    keywords: ["Trickster", "List", "Cleverness", "Strategie", "Manipulation"],
    center: "Herz-Zentrum",
    line: 6,
    hexagram: "Der Große Zähmende",
    meaning: "Die Energie des Tricksters und der List. Du bist hier, um clever und strategisch zu sein.",
    shadow: "Übertriebene Manipulation oder mangelnde Cleverness",
    gift: "Natürliche Cleverness und strategisches Denken",
    siddhi: "Göttliche Weisheit und Strategie",
    bodygraph: { position: { x: 55, y: 60 }, color: "#f97316" }
  },
  27: {
    number: 27,
    name: "Die Fürsorge",
    description: "Das Tor der Fürsorge und des Schutzes. Es bringt die Energie der Nährung und des Schutzes.",
    keywords: ["Fürsorge", "Schutz", "Nährung", "Mutter", "Pflege"],
    center: "Milz-Zentrum",
    line: 1,
    hexagram: "Die Ernährung",
    meaning: "Die Energie der Fürsorge und des Schutzes. Du bist hier, um zu nähren und zu schützen.",
    shadow: "Übertriebene Fürsorge oder Vernachlässigung",
    gift: "Natürliche Fürsorge und Schutzfähigkeit",
    siddhi: "Göttliche Nährung und Schutz",
    bodygraph: { position: { x: 40, y: 50 }, color: "#ec4899" }
  },
  28: {
    number: 28,
    name: "Der Spieler",
    description: "Das Tor des Spielers und des Abenteuers. Es bringt die Energie des Spiels und der Entdeckung.",
    keywords: ["Spieler", "Abenteuer", "Spiel", "Entdeckung", "Risiko"],
    center: "Milz-Zentrum",
    line: 2,
    hexagram: "Der Große Übergewichtige",
    meaning: "Die Energie des Spielers und des Abenteuers. Du bist hier, um zu spielen und zu entdecken.",
    shadow: "Übertriebenes Risiko oder mangelnde Abenteuerlust",
    gift: "Natürliche Spielerqualitäten und Abenteuerlust",
    siddhi: "Göttliches Spiel und Entdeckung",
    bodygraph: { position: { x: 60, y: 50 }, color: "#84cc16" }
  },
  29: {
    number: 29,
    name: "Die Entschlossenheit",
    description: "Das Tor der Entschlossenheit und des Engagements. Es bringt die Energie der Hingabe und des Engagements.",
    keywords: ["Entschlossenheit", "Engagement", "Hingabe", "Verpflichtung", "Durchhaltevermögen"],
    center: "Sakral-Zentrum",
    line: 3,
    hexagram: "Das Abgründige",
    meaning: "Die Energie der Entschlossenheit und des Engagements. Du bist hier, um entschlossen und engagiert zu sein.",
    shadow: "Übertriebenes Engagement oder mangelnde Entschlossenheit",
    gift: "Natürliche Entschlossenheit und Engagement",
    siddhi: "Göttliche Hingabe und Verpflichtung",
    bodygraph: { position: { x: 50, y: 70 }, color: "#ef4444" }
  },
  30: {
    number: 30,
    name: "Das Feuer",
    description: "Das Tor des Feuers und der Leidenschaft. Es bringt die Energie der Leidenschaft und des Feuers.",
    keywords: ["Feuer", "Leidenschaft", "Energie", "Begeisterung", "Intensität"],
    center: "Sakral-Zentrum",
    line: 4,
    hexagram: "Das Feuer",
    meaning: "Die Energie des Feuers und der Leidenschaft. Du bist hier, um leidenschaftlich und energisch zu sein.",
    shadow: "Übertriebene Leidenschaft oder mangelnde Energie",
    gift: "Natürliche Leidenschaft und Energie",
    siddhi: "Göttliches Feuer und Begeisterung",
    bodygraph: { position: { x: 50, y: 80 }, color: "#f59e0b" }
  },
  31: {
    number: 31,
    name: "Der Einfluss",
    description: "Das Tor des Einflusses und der Führung. Es bringt die Energie der natürlichen Autorität und des Einflusses.",
    keywords: ["Einfluss", "Führung", "Autorität", "Macht", "Verantwortung"],
    center: "Kehle-Zentrum",
    line: 1,
    hexagram: "Der Einfluss",
    meaning: "Die Energie des Einflusses und der Führung. Du bist hier, um Einfluss zu nehmen und zu führen.",
    shadow: "Machtmissbrauch oder mangelnder Einfluss",
    gift: "Natürliche Führungsqualitäten und Einflussnahme",
    siddhi: "Göttlicher Einfluss und Führung",
    bodygraph: { position: { x: 50, y: 35 }, color: "#06b6d4" }
  },
  32: {
    number: 32,
    name: "Die Dauer",
    description: "Das Tor der Dauer und Beständigkeit. Es bringt die Energie der Ausdauer und Beständigkeit.",
    keywords: ["Dauer", "Beständigkeit", "Ausdauer", "Persistenz", "Kontinuität"],
    center: "Milz-Zentrum",
    line: 2,
    hexagram: "Die Dauer",
    meaning: "Die Energie der Dauer und Beständigkeit. Du bist hier, um ausdauernd und beständig zu sein.",
    shadow: "Mangelnde Ausdauer oder übertriebene Starrheit",
    gift: "Natürliche Ausdauer und Beständigkeit",
    siddhi: "Göttliche Dauer und Beständigkeit",
    bodygraph: { position: { x: 35, y: 50 }, color: "#10b981" }
  },
  33: {
    number: 33,
    name: "Der Rückzug",
    description: "Das Tor des Rückzugs und der Reflexion. Es bringt die Energie des Rückzugs und der inneren Arbeit.",
    keywords: ["Rückzug", "Reflexion", "Stille", "Innere Arbeit", "Wissen"],
    center: "Kehle-Zentrum",
    line: 3,
    hexagram: "Der Rückzug",
    meaning: "Die Energie des Rückzugs und der Reflexion. Du bist hier, um dich zurückzuziehen und zu reflektieren.",
    shadow: "Übertriebener Rückzug oder mangelnde Reflexion",
    gift: "Natürliche Fähigkeit zum Rückzug und zur Reflexion",
    siddhi: "Göttlicher Rückzug und Weisheit",
    bodygraph: { position: { x: 50, y: 45 }, color: "#8b5cf6" }
  },
  34: {
    number: 34,
    name: "Die Kraft",
    description: "Das Tor der Kraft und Macht. Es bringt die Energie der körperlichen Kraft und Macht.",
    keywords: ["Kraft", "Macht", "Stärke", "Energie", "Durchsetzung"],
    center: "Sakral-Zentrum",
    line: 4,
    hexagram: "Die Kraft",
    meaning: "Die Energie der Kraft und Macht. Du bist hier, um kraftvoll und mächtig zu sein.",
    shadow: "Machtmissbrauch oder mangelnde Kraft",
    gift: "Natürliche Kraft und Macht",
    siddhi: "Göttliche Kraft und Macht",
    bodygraph: { position: { x: 50, y: 75 }, color: "#ef4444" }
  },
  35: {
    number: 35,
    name: "Der Fortschritt",
    description: "Das Tor des Fortschritts und der Entwicklung. Es bringt die Energie des Fortschritts und der Evolution.",
    keywords: ["Fortschritt", "Entwicklung", "Evolution", "Wachstum", "Veränderung"],
    center: "Sakral-Zentrum",
    line: 5,
    hexagram: "Der Fortschritt",
    meaning: "Die Energie des Fortschritts und der Entwicklung. Du bist hier, um Fortschritt zu machen und dich zu entwickeln.",
    shadow: "Mangelnder Fortschritt oder übertriebene Veränderung",
    gift: "Natürliche Fähigkeit zum Fortschritt und zur Entwicklung",
    siddhi: "Göttlicher Fortschritt und Evolution",
    bodygraph: { position: { x: 50, y: 65 }, color: "#f59e0b" }
  },
  36: {
    number: 36,
    name: "Die Dunkelheit",
    description: "Das Tor der Dunkelheit und Krise. Es bringt die Energie der Transformation durch Dunkelheit.",
    keywords: ["Dunkelheit", "Krise", "Transformation", "Schatten", "Wachstum"],
    center: "Sakral-Zentrum",
    line: 6,
    hexagram: "Die Dunkelheit",
    meaning: "Die Energie der Dunkelheit und Krise. Du bist hier, um durch Dunkelheit zu transformieren.",
    shadow: "Übertriebene Dunkelheit oder Vermeidung von Krisen",
    gift: "Natürliche Fähigkeit zur Transformation durch Krisen",
    siddhi: "Göttliche Transformation und Erleuchtung",
    bodygraph: { position: { x: 50, y: 85 }, color: "#6b7280" }
  },
  37: {
    number: 37,
    name: "Die Familie",
    description: "Das Tor der Familie und Gemeinschaft. Es bringt die Energie der Familie und des Zusammenhalts.",
    keywords: ["Familie", "Gemeinschaft", "Zusammenhalt", "Unterstützung", "Liebe"],
    center: "Herz-Zentrum",
    line: 1,
    hexagram: "Die Familie",
    meaning: "Die Energie der Familie und Gemeinschaft. Du bist hier, um Familie und Gemeinschaft zu stärken.",
    shadow: "Übertriebene Familienbindung oder mangelnder Zusammenhalt",
    gift: "Natürliche Fähigkeit, Familie und Gemeinschaft zu stärken",
    siddhi: "Göttliche Familie und universelle Liebe",
    bodygraph: { position: { x: 45, y: 55 }, color: "#ec4899" }
  },
  38: {
    number: 38,
    name: "Der Kämpfer",
    description: "Das Tor des Kämpfers und der Rebellion. Es bringt die Energie des Kampfes und der Rebellion.",
    keywords: ["Kämpfer", "Rebellion", "Kampf", "Widerstand", "Gerechtigkeit"],
    center: "Herz-Zentrum",
    line: 2,
    hexagram: "Der Kämpfer",
    meaning: "Die Energie des Kämpfers und der Rebellion. Du bist hier, um zu kämpfen und zu rebellieren.",
    shadow: "Übertriebener Kampf oder mangelnder Widerstand",
    gift: "Natürliche Kampfqualitäten und Gerechtigkeitssinn",
    siddhi: "Göttlicher Kampf und universelle Gerechtigkeit",
    bodygraph: { position: { x: 55, y: 55 }, color: "#ef4444" }
  },
  39: {
    number: 39,
    name: "Die Provokation",
    description: "Das Tor der Provokation und Herausforderung. Es bringt die Energie der Provokation und des Durchbruchs.",
    keywords: ["Provokation", "Herausforderung", "Durchbruch", "Störung", "Veränderung"],
    center: "Kehle-Zentrum",
    line: 3,
    hexagram: "Die Provokation",
    meaning: "Die Energie der Provokation und Herausforderung. Du bist hier, um zu provozieren und Durchbrüche zu schaffen.",
    shadow: "Übertriebene Provokation oder mangelnde Herausforderung",
    gift: "Natürliche Fähigkeit zur Provokation und zum Durchbruch",
    siddhi: "Göttliche Provokation und Transformation",
    bodygraph: { position: { x: 50, y: 40 }, color: "#8b5cf6" }
  },
  40: {
    number: 40,
    name: "Die Befreiung",
    description: "Das Tor der Befreiung und des Loslassens. Es bringt die Energie der Befreiung und des Loslassens.",
    keywords: ["Befreiung", "Loslassen", "Freiheit", "Entlastung", "Erleichterung"],
    center: "Herz-Zentrum",
    line: 4,
    hexagram: "Die Befreiung",
    meaning: "Die Energie der Befreiung und des Loslassens. Du bist hier, um zu befreien und loszulassen.",
    shadow: "Übertriebene Befreiung oder mangelndes Loslassen",
    gift: "Natürliche Fähigkeit zur Befreiung und zum Loslassen",
    siddhi: "Göttliche Befreiung und universelle Freiheit",
    bodygraph: { position: { x: 50, y: 50 }, color: "#10b981" }
  },
  41: {
    number: 41,
    name: "Die Verringerung",
    description: "Das Tor der Verringerung und Vereinfachung. Es bringt die Energie der Vereinfachung und Reduktion.",
    keywords: ["Verringerung", "Vereinfachung", "Reduktion", "Minimalismus", "Fokus"],
    center: "Herz-Zentrum",
    line: 5,
    hexagram: "Die Verringerung",
    meaning: "Die Energie der Verringerung und Vereinfachung. Du bist hier, um zu vereinfachen und zu reduzieren.",
    shadow: "Übertriebene Reduktion oder mangelnde Vereinfachung",
    gift: "Natürliche Fähigkeit zur Vereinfachung und Reduktion",
    siddhi: "Göttliche Vereinfachung und Essenz",
    bodygraph: { position: { x: 50, y: 45 }, color: "#f59e0b" }
  },
  42: {
    number: 42,
    name: "Das Wachstum",
    description: "Das Tor des Wachstums und der Expansion. Es bringt die Energie des Wachstums und der Expansion.",
    keywords: ["Wachstum", "Expansion", "Entwicklung", "Vermehrung", "Fülle"],
    center: "Herz-Zentrum",
    line: 6,
    hexagram: "Das Wachstum",
    meaning: "Die Energie des Wachstums und der Expansion. Du bist hier, um zu wachsen und dich zu expandieren.",
    shadow: "Übertriebenes Wachstum oder mangelnde Expansion",
    gift: "Natürliche Fähigkeit zum Wachstum und zur Expansion",
    siddhi: "Göttliches Wachstum und universelle Fülle",
    bodygraph: { position: { x: 50, y: 60 }, color: "#84cc16" }
  },
  43: {
    number: 43,
    name: "Der Durchbruch",
    description: "Das Tor des Durchbruchs und der Erkenntnis. Es bringt die Energie des Durchbruchs und der Erkenntnis.",
    keywords: ["Durchbruch", "Erkenntnis", "Einsicht", "Verstehen", "Wissen"],
    center: "Ajna-Zentrum",
    line: 1,
    hexagram: "Der Durchbruch",
    meaning: "Die Energie des Durchbruchs und der Erkenntnis. Du bist hier, um Durchbrüche zu erleben und Erkenntnisse zu gewinnen.",
    shadow: "Übertriebene Erkenntnis oder mangelnder Durchbruch",
    gift: "Natürliche Fähigkeit zu Durchbrüchen und Erkenntnissen",
    siddhi: "Göttliche Erkenntnis und universelles Wissen",
    bodygraph: { position: { x: 50, y: 20 }, color: "#8b5cf6" }
  },
  44: {
    number: 44,
    name: "Die Annäherung",
    description: "Das Tor der Annäherung und des Herangehens. Es bringt die Energie der Annäherung und des Herangehens.",
    keywords: ["Annäherung", "Herangehen", "Nähe", "Beziehung", "Verbindung"],
    center: "Kehle-Zentrum",
    line: 2,
    hexagram: "Die Annäherung",
    meaning: "Die Energie der Annäherung und des Herangehens. Du bist hier, um dich zu nähern und Beziehungen aufzubauen.",
    shadow: "Übertriebene Annäherung oder mangelnde Nähe",
    gift: "Natürliche Fähigkeit zur Annäherung und zum Herangehen",
    siddhi: "Göttliche Annäherung und universelle Verbindung",
    bodygraph: { position: { x: 50, y: 35 }, color: "#06b6d4" }
  },
  45: {
    number: 45,
    name: "Der Sammler",
    description: "Das Tor des Sammlers und der Anhäufung. Es bringt die Energie des Sammelns und der Anhäufung.",
    keywords: ["Sammler", "Anhäufung", "Sammlung", "Reichtum", "Fülle"],
    center: "Herz-Zentrum",
    line: 3,
    hexagram: "Der Sammler",
    meaning: "Die Energie des Sammlers und der Anhäufung. Du bist hier, um zu sammeln und anzuhäufen.",
    shadow: "Übertriebene Anhäufung oder mangelndes Sammeln",
    gift: "Natürliche Fähigkeit zum Sammeln und zur Anhäufung",
    siddhi: "Göttliches Sammeln und universelle Fülle",
    bodygraph: { position: { x: 50, y: 50 }, color: "#f59e0b" }
  },
  46: {
    number: 46,
    name: "Die Entschlossenheit",
    description: "Das Tor der Entschlossenheit und des Engagements. Es bringt die Energie der Hingabe und des Engagements.",
    keywords: ["Entschlossenheit", "Engagement", "Hingabe", "Verpflichtung", "Durchhaltevermögen"],
    center: "G-Zentrum",
    line: 4,
    hexagram: "Die Entschlossenheit",
    meaning: "Die Energie der Entschlossenheit und des Engagements. Du bist hier, um entschlossen und engagiert zu sein.",
    shadow: "Übertriebenes Engagement oder mangelnde Entschlossenheit",
    gift: "Natürliche Entschlossenheit und Engagement",
    siddhi: "Göttliche Hingabe und universelle Verpflichtung",
    bodygraph: { position: { x: 50, y: 55 }, color: "#10b981" }
  },
  47: {
    number: 47,
    name: "Die Verwirrung",
    description: "Das Tor der Verwirrung und des Durchbruchs. Es bringt die Energie der Verwirrung und des Durchbruchs.",
    keywords: ["Verwirrung", "Durchbruch", "Chaos", "Transformation", "Erkenntnis"],
    center: "Ajna-Zentrum",
    line: 5,
    hexagram: "Die Verwirrung",
    meaning: "Die Energie der Verwirrung und des Durchbruchs. Du bist hier, um durch Verwirrung zu Durchbrüchen zu gelangen.",
    shadow: "Übertriebene Verwirrung oder mangelnder Durchbruch",
    gift: "Natürliche Fähigkeit zur Transformation durch Verwirrung",
    siddhi: "Göttliche Verwirrung und universelle Erkenntnis",
    bodygraph: { position: { x: 50, y: 25 }, color: "#8b5cf6" }
  },
  48: {
    number: 48,
    name: "Der Brunnen",
    description: "Das Tor des Brunnens und der Tiefe. Es bringt die Energie der Tiefe und des Wissens.",
    keywords: ["Brunnen", "Tiefe", "Wissen", "Weisheit", "Verstehen"],
    center: "Milz-Zentrum",
    line: 6,
    hexagram: "Der Brunnen",
    meaning: "Die Energie des Brunnens und der Tiefe. Du bist hier, um tiefes Wissen und Weisheit zu erlangen.",
    shadow: "Übertriebene Tiefe oder mangelndes Wissen",
    gift: "Natürliche Fähigkeit zu tiefem Wissen und Weisheit",
    siddhi: "Göttlicher Brunnen und universelle Weisheit",
    bodygraph: { position: { x: 40, y: 50 }, color: "#10b981" }
  },
  49: {
    number: 49,
    name: "Die Revolution",
    description: "Das Tor der Revolution und des Wandels. Es bringt die Energie der Revolution und des radikalen Wandels.",
    keywords: ["Revolution", "Wandel", "Veränderung", "Transformation", "Neubeginn"],
    center: "Kehle-Zentrum",
    line: 1,
    hexagram: "Die Revolution",
    meaning: "Die Energie der Revolution und des Wandels. Du bist hier, um Revolutionen zu schaffen und Wandel zu bewirken.",
    shadow: "Übertriebene Revolution oder mangelnder Wandel",
    gift: "Natürliche Fähigkeit zur Revolution und zum Wandel",
    siddhi: "Göttliche Revolution und universeller Wandel",
    bodygraph: { position: { x: 50, y: 40 }, color: "#ef4444" }
  },
  50: {
    number: 50,
    name: "Der Kessel",
    description: "Das Tor des Kessels und der Transformation. Es bringt die Energie der Transformation und des Kochens.",
    keywords: ["Kessel", "Transformation", "Kochen", "Nährung", "Heilung"],
    center: "Milz-Zentrum",
    line: 2,
    hexagram: "Der Kessel",
    meaning: "Die Energie des Kessels und der Transformation. Du bist hier, um zu transformieren und zu nähren.",
    shadow: "Übertriebene Transformation oder mangelnde Nährung",
    gift: "Natürliche Fähigkeit zur Transformation und Nährung",
    siddhi: "Göttlicher Kessel und universelle Heilung",
    bodygraph: { position: { x: 35, y: 50 }, color: "#f59e0b" }
  },
  51: {
    number: 51,
    name: "Das Erschüttern",
    description: "Das Tor des Erschütterns und der Erweckung. Es bringt die Energie des Erschütterns und der Erweckung.",
    keywords: ["Erschüttern", "Erweckung", "Schock", "Aufwachen", "Bewusstsein"],
    center: "Herz-Zentrum",
    line: 3,
    hexagram: "Das Erschüttern",
    meaning: "Die Energie des Erschütterns und der Erweckung. Du bist hier, um zu erschüttern und zu erwecken.",
    shadow: "Übertriebenes Erschüttern oder mangelnde Erweckung",
    gift: "Natürliche Fähigkeit zum Erschüttern und zur Erweckung",
    siddhi: "Göttliches Erschüttern und universelle Erweckung",
    bodygraph: { position: { x: 50, y: 50 }, color: "#ef4444" }
  },
  52: {
    number: 52,
    name: "Das Stillehalten",
    description: "Das Tor des Stillehaltens und der Meditation. Es bringt die Energie der Stille und der Meditation.",
    keywords: ["Stillehalten", "Meditation", "Stille", "Ruhe", "Bewusstsein"],
    center: "Milz-Zentrum",
    line: 4,
    hexagram: "Das Stillehalten",
    meaning: "Die Energie des Stillehaltens und der Meditation. Du bist hier, um stillzuhalten und zu meditieren.",
    shadow: "Übertriebene Stille oder mangelnde Meditation",
    gift: "Natürliche Fähigkeit zum Stillehalten und zur Meditation",
    siddhi: "Göttliche Stille und universelle Meditation",
    bodygraph: { position: { x: 40, y: 50 }, color: "#10b981" }
  },
  53: {
    number: 53,
    name: "Die Entwicklung",
    description: "Das Tor der Entwicklung und des Wachstums. Es bringt die Energie der Entwicklung und des allmählichen Wachstums.",
    keywords: ["Entwicklung", "Wachstum", "Fortschritt", "Evolution", "Reifung"],
    center: "Kehle-Zentrum",
    line: 5,
    hexagram: "Die Entwicklung",
    meaning: "Die Energie der Entwicklung und des Wachstums. Du bist hier, um dich zu entwickeln und zu wachsen.",
    shadow: "Mangelnde Entwicklung oder übertriebenes Wachstum",
    gift: "Natürliche Fähigkeit zur Entwicklung und zum Wachstum",
    siddhi: "Göttliche Entwicklung und universelles Wachstum",
    bodygraph: { position: { x: 50, y: 40 }, color: "#84cc16" }
  },
  54: {
    number: 54,
    name: "Das heiratende Mädchen",
    description: "Das Tor des heiratenden Mädchens und der Verbindung. Es bringt die Energie der Verbindung und der Partnerschaft.",
    keywords: ["Heirat", "Verbindung", "Partnerschaft", "Liebe", "Einheit"],
    center: "Herz-Zentrum",
    line: 6,
    hexagram: "Das heiratende Mädchen",
    meaning: "Die Energie des heiratenden Mädchens und der Verbindung. Du bist hier, um Verbindungen und Partnerschaften zu schaffen.",
    shadow: "Übertriebene Verbindung oder mangelnde Partnerschaft",
    gift: "Natürliche Fähigkeit zur Verbindung und Partnerschaft",
    siddhi: "Göttliche Verbindung und universelle Liebe",
    bodygraph: { position: { x: 50, y: 50 }, color: "#ec4899" }
  },
  55: {
    number: 55,
    name: "Die Fülle",
    description: "Das Tor der Fülle und des Überflusses. Es bringt die Energie der Fülle und des Überflusses.",
    keywords: ["Fülle", "Überfluss", "Reichtum", "Abundanz", "Wohlstand"],
    center: "Sakral-Zentrum",
    line: 1,
    hexagram: "Die Fülle",
    meaning: "Die Energie der Fülle und des Überflusses. Du bist hier, um Fülle und Überfluss zu erleben.",
    shadow: "Übertriebene Fülle oder mangelnder Überfluss",
    gift: "Natürliche Fähigkeit zur Fülle und zum Überfluss",
    siddhi: "Göttliche Fülle und universeller Überfluss",
    bodygraph: { position: { x: 50, y: 70 }, color: "#f59e0b" }
  },
  56: {
    number: 56,
    name: "Der Wanderer",
    description: "Das Tor des Wanderers und der Reise. Es bringt die Energie des Reisens und der Entdeckung.",
    keywords: ["Wanderer", "Reise", "Entdeckung", "Abenteuer", "Erfahrung"],
    center: "Kehle-Zentrum",
    line: 2,
    hexagram: "Der Wanderer",
    meaning: "Die Energie des Wanderers und der Reise. Du bist hier, um zu reisen und zu entdecken.",
    shadow: "Übertriebenes Reisen oder mangelnde Entdeckung",
    gift: "Natürliche Fähigkeit zum Reisen und zur Entdeckung",
    siddhi: "Göttlicher Wanderer und universelle Entdeckung",
    bodygraph: { position: { x: 50, y: 40 }, color: "#06b6d4" }
  },
  57: {
    number: 57,
    name: "Das Sanfte",
    description: "Das Tor des Sanften und der Milde. Es bringt die Energie der Sanftheit und der Milde.",
    keywords: ["Sanft", "Milde", "Zartheit", "Empfindsamkeit", "Harmonie"],
    center: "Milz-Zentrum",
    line: 3,
    hexagram: "Das Sanfte",
    meaning: "Die Energie des Sanften und der Milde. Du bist hier, um sanft und mild zu sein.",
    shadow: "Übertriebene Sanftheit oder mangelnde Milde",
    gift: "Natürliche Sanftheit und Milde",
    siddhi: "Göttliche Sanftheit und universelle Harmonie",
    bodygraph: { position: { x: 40, y: 50 }, color: "#10b981" }
  },
  58: {
    number: 58,
    name: "Das Freudige",
    description: "Das Tor des Freudigen und der Freude. Es bringt die Energie der Freude und des Glücks.",
    keywords: ["Freudig", "Freude", "Glück", "Begeisterung", "Lebensfreude"],
    center: "Herz-Zentrum",
    line: 4,
    hexagram: "Das Freudige",
    meaning: "Die Energie des Freudigen und der Freude. Du bist hier, um freudig und glücklich zu sein.",
    shadow: "Übertriebene Freude oder mangelndes Glück",
    gift: "Natürliche Freude und Glücksfähigkeit",
    siddhi: "Göttliche Freude und universelles Glück",
    bodygraph: { position: { x: 50, y: 50 }, color: "#f59e0b" }
  },
  59: {
    number: 59,
    name: "Die Auflösung",
    description: "Das Tor der Auflösung und des Loslassens. Es bringt die Energie der Auflösung und des Loslassens.",
    keywords: ["Auflösung", "Loslassen", "Befreiung", "Entspannung", "Erleichterung"],
    center: "Sakral-Zentrum",
    line: 5,
    hexagram: "Die Auflösung",
    meaning: "Die Energie der Auflösung und des Loslassens. Du bist hier, um aufzulösen und loszulassen.",
    shadow: "Übertriebene Auflösung oder mangelndes Loslassen",
    gift: "Natürliche Fähigkeit zur Auflösung und zum Loslassen",
    siddhi: "Göttliche Auflösung und universelle Befreiung",
    bodygraph: { position: { x: 50, y: 70 }, color: "#06b6d4" }
  },
  60: {
    number: 60,
    name: "Die Beschränkung",
    description: "Das Tor der Beschränkung und der Grenzen. Es bringt die Energie der Beschränkung und der Grenzen.",
    keywords: ["Beschränkung", "Grenzen", "Limitierung", "Struktur", "Ordnung"],
    center: "Sakral-Zentrum",
    line: 6,
    hexagram: "Die Beschränkung",
    meaning: "Die Energie der Beschränkung und der Grenzen. Du bist hier, um Grenzen zu setzen und zu strukturieren.",
    shadow: "Übertriebene Beschränkung oder mangelnde Grenzen",
    gift: "Natürliche Fähigkeit zur Beschränkung und zu Grenzen",
    siddhi: "Göttliche Beschränkung und universelle Ordnung",
    bodygraph: { position: { x: 50, y: 80 }, color: "#6b7280" }
  },
  61: {
    number: 61,
    name: "Die innere Wahrheit",
    description: "Das Tor der inneren Wahrheit und des Wissens. Es bringt die Energie der inneren Wahrheit und des Wissens.",
    keywords: ["Innere Wahrheit", "Wissen", "Erkenntnis", "Verstehen", "Weisheit"],
    center: "Ajna-Zentrum",
    line: 1,
    hexagram: "Die innere Wahrheit",
    meaning: "Die Energie der inneren Wahrheit und des Wissens. Du bist hier, um innere Wahrheit und Wissen zu erlangen.",
    shadow: "Übertriebene Wahrheit oder mangelndes Wissen",
    gift: "Natürliche Fähigkeit zur inneren Wahrheit und zum Wissen",
    siddhi: "Göttliche Wahrheit und universelles Wissen",
    bodygraph: { position: { x: 50, y: 25 }, color: "#8b5cf6" }
  },
  62: {
    number: 62,
    name: "Die Kleinheit",
    description: "Das Tor der Kleinheit und der Bescheidenheit. Es bringt die Energie der Kleinheit und der Bescheidenheit.",
    keywords: ["Kleinheit", "Bescheidenheit", "Einfachheit", "Demut", "Natürlichkeit"],
    center: "Kehle-Zentrum",
    line: 2,
    hexagram: "Die Kleinheit",
    meaning: "Die Energie der Kleinheit und der Bescheidenheit. Du bist hier, um klein und bescheiden zu sein.",
    shadow: "Übertriebene Kleinheit oder mangelnde Bescheidenheit",
    gift: "Natürliche Kleinheit und Bescheidenheit",
    siddhi: "Göttliche Kleinheit und universelle Bescheidenheit",
    bodygraph: { position: { x: 50, y: 40 }, color: "#10b981" }
  },
  63: {
    number: 63,
    name: "Die Nachfrage",
    description: "Das Tor der Nachfrage und des Zweifels. Es bringt die Energie der Nachfrage und des Zweifels.",
    keywords: ["Nachfrage", "Zweifel", "Fragen", "Unsicherheit", "Verstehen"],
    center: "Ajna-Zentrum",
    line: 3,
    hexagram: "Die Nachfrage",
    meaning: "Die Energie der Nachfrage und des Zweifels. Du bist hier, um zu fragen und zu zweifeln.",
    shadow: "Übertriebene Nachfrage oder mangelnder Zweifel",
    gift: "Natürliche Fähigkeit zur Nachfrage und zum Zweifel",
    siddhi: "Göttliche Nachfrage und universeller Zweifel",
    bodygraph: { position: { x: 50, y: 25 }, color: "#8b5cf6" }
  },
  64: {
    number: 64,
    name: "Die Unvollendung",
    description: "Das Tor der Unvollendung und des Potentials. Es bringt die Energie der Unvollendung und des Potentials.",
    keywords: ["Unvollendung", "Potential", "Möglichkeit", "Beginn", "Entwicklung"],
    center: "Ajna-Zentrum",
    line: 4,
    hexagram: "Die Unvollendung",
    meaning: "Die Energie der Unvollendung und des Potentials. Du bist hier, um Potential zu erkennen und zu entwickeln.",
    shadow: "Übertriebene Unvollendung oder mangelndes Potential",
    gift: "Natürliche Fähigkeit zur Potentialerkennung und -entwicklung",
    siddhi: "Göttliche Unvollendung und universelles Potential",
    bodygraph: { position: { x: 50, y: 25 }, color: "#8b5cf6" }
  }
};

// Funktionen für Tor-Daten
export const getGateData = (gateNumber: number): GateData | null => {
  return gatesData[gateNumber] || null;
};

export const getAllGates = (): GateData[] => {
  return Object.values(gatesData);
};

export const getGatesByCenter = (center: string): GateData[] => {
  return Object.values(gatesData).filter(gate => gate.center === center);
};

export const getGatesByKeywords = (keyword: string): GateData[] => {
  return Object.values(gatesData).filter(gate => 
    gate.keywords.some(k => k.toLowerCase().includes(keyword.toLowerCase()))
  );
};

